using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Godot;

// Scene root. Owns the GameState and orchestrates the first tick on startup.
//
// Lifetime model:
//   - _Ready fires synchronously on the Godot main thread; we MUST NOT await
//     anything here or we block frame N (Godot's lifecycle methods are not
//     async-aware, despite the C# bindings tolerating the signature).
//   - StartNewGame returns a Task we fire-and-forget with `_ =`. Any continuation
//     after `await` may resume off the main thread — we marshal node mutations
//     back to the main thread via Callable.From(...).CallDeferred().
//   - _ExitTree cancels the in-flight token so an HTTP timeout doesn't keep the
//     process alive past scene teardown.
//
// J7 carousel migration:
//   The single info panel + character pair (J3c / J3b / J4a) is replaced by a
//   3-slot MissionCarouselPanel that owns its own (card, pawn) pool. Main no
//   longer holds direct refs to _infoPanel and _halfgateCharacter; it holds
//   a single _carousel reference and delegates display + slot wiring there.
//   The wheel handler stays here (Main owns _activeMissionIndex; the carousel
//   is a passive view) but its body shrinks to: forward delta to the carousel,
//   read back the new index, consume input as needed.
public partial class Main : Node2D
{
	private GameState _state = null!;
	private MissionGridOverlay _overlay = null!;
	private MissionIsoPawn _halfgatePawn = null!;
	private MissionCarouselPanel _carousel = null!;
	private Button _nextTickButton = null!;
	private readonly CancellationTokenSource _cts = new();

	// Monotonic tick counter sent on every /api/world/tick. Starts at 1 so the
	// first call (StartNewGame) sends tick=1, the second (first Next Tick press)
	// sends tick=2, etc. Backend's WAYFINDERS_DEBUG_TICKS env var lists the
	// tick values that should emit a debug mission, so this counter MUST stay
	// in lockstep with what Didier configures there.
	//
	// Reset to 1 inside StartNewGame so a future "New Game" path stays clean.
	// Mutated only after a successful HTTP call inside DoTickAsync (the +1
	// happens AFTER the request, not before, so a failed call doesn't burn a
	// tick number).
	private int _currentTick = 1;

	// J4a / J7: index into GameState.ActiveMissions of the mission currently
	// shown by the carousel's Active slot. Wheel-up / wheel-down navigate this
	// index; the carousel rebinds prev/active/next around the new value.
	// Clamps at the bounds (no wrap) so the edges feel like a finite list, not
	// an infinite cycle.
	//
	// Why Main holds this (and not the carousel): the carousel is a passive
	// view. The authoritative state — the mission list, the active index —
	// lives on Main alongside _state. The carousel reads (missions, index) on
	// every SetActiveMission call and produces a navigation result on every
	// TryNavigate call; Main keeps the canonical _activeMissionIndex in sync
	// with the carousel's internal cache by reading back ActiveIndex after
	// each TryNavigate.
	private int _activeMissionIndex = 0;

	public override void _Ready()
	{
		GD.Print("Hello Wayfinders");

		_state = new GameState();
		_overlay = GetNode<MissionGridOverlay>("WorldLayer/MissionGridOverlay");
		// The Halfgate "pawn" is a board element anchored on PawnLayer — no
		// separate CanvasLayer panel. Future board elements (other POIs,
		// characters, props) follow the same pattern: child of PawnLayer,
		// positioned via PawnLayer.MapToLocal(cell).
		_halfgatePawn = GetNode<MissionIsoPawn>(
			"BoardLayer/BoardRoot/PawnLayer/MissionIsoPawn");

		// J7: the carousel owns the 3 card slots and their 3 character pawns.
		// Main only holds a single reference here; per-slot refs live on the
		// carousel (resolved from its [Export] NodePaths in its _Ready).
		_carousel = GetNode<MissionCarouselPanel>(
			"BoardLayer/BoardRoot/PawnLayer/MissionCarouselPanel");

		// J4a test harness: a screen-stable Button on a high-layer CanvasLayer
		// (UILayer, layer=100, above BoardLayer's layer=10) that fires another
		// /api/world/tick on demand. Used to accumulate multiple missions
		// interactively so the wheel-navigation path can be exercised without
		// editing code between presses. NOT a production UI element.
		_nextTickButton = GetNode<Button>("UILayer/NextTickButton");
		_nextTickButton.Pressed += OnNextTickPressed;

		// Wire mission-selection signals to the iso pawn's visibility.
		// We use method-group subscription (typed events generated by the
		// [Signal] attribute) instead of Connect-by-StringName so the C#
		// compiler verifies the handler signature, and so _ExitTree can
		// disconnect symmetrically with -=.
		_overlay.MissionCellSelected   += OnMissionCellSelected;
		_overlay.MissionCellDeselected += OnMissionCellDeselected;

		// Pawn-companion wiring. Engaged fires the instant the user hovers the
		// painted silhouette of the pawn while it's visible; Released fires
		// when the hover leaves OR when the pawn is force-hidden mid-engaged.
		// On Engaged we refresh the carousel (so the latest mission list /
		// recruit target is shown) then show it; on Released we hide it.
		_halfgatePawn.Engaged  += OnHalfgatePawnEngaged;
		_halfgatePawn.Released += OnHalfgatePawnReleased;

		// Fire-and-forget — see class comment for why we don't await here.
		_ = StartNewGame();
	}

	public override void _ExitTree()
	{
		// Signal disconnection discipline: the publisher (MissionGridOverlay)
		// outlives nobody here (it's a sibling, freed at the same time), but
		// we still disconnect to (a) avoid the warning Godot emits when a
		// publisher fires into a freed receiver during the tear-down frame,
		// and (b) keep the symmetry that other nodes can rely on if they ever
		// inherit from Main.
		if (GodotObject.IsInstanceValid(_overlay))
		{
			_overlay.MissionCellSelected   -= OnMissionCellSelected;
			_overlay.MissionCellDeselected -= OnMissionCellDeselected;
		}

		if (GodotObject.IsInstanceValid(_halfgatePawn))
		{
			_halfgatePawn.Engaged  -= OnHalfgatePawnEngaged;
			_halfgatePawn.Released -= OnHalfgatePawnReleased;
		}

		if (GodotObject.IsInstanceValid(_nextTickButton))
		{
			_nextTickButton.Pressed -= OnNextTickPressed;
		}

		// Signal any in-flight HTTP work to abort. Without this, a slow backend
		// can keep the Task alive after the scene is gone and the continuation
		// will then touch freed nodes.
		_cts.Cancel();
		_cts.Dispose();
	}

	// J4a / J7: wheel-up / wheel-down navigation across ActiveMissions while
	// the carousel is visible.
	//
	// Gating: we act ONLY when the carousel's active card is visible. The
	// carousel is visible iff the pawn is currently engaged (hover-driven),
	// which is the only state in which "which mission am I looking at" is a
	// meaningful question for the user. When the carousel is hidden, we leave
	// the wheel event un-handled so any future zoom/pan-on-wheel feature can
	// pick it up.
	//
	// _UnhandledInput (not _Input): foreground widgets — MissionGridOverlay's
	// click/hover and MissionIsoPawn's hover — handle in _Input. The wheel
	// navigation is conceptually a background/global gesture (it's the
	// carousel reacting, not a node the cursor is over), so _UnhandledInput
	// is the correct layer per the standard Godot input-layering pattern.
	//
	// Delegation: the actual navigation logic — clamp, rebind, animate — lives
	// on MissionCarouselPanel.TryNavigate. Main just reads the wheel event,
	// forwards the delta, reads back the new index, and consumes the input
	// based on the NavigateResult.
	public override void _UnhandledInput(InputEvent @event)
	{
		if (@event is not InputEventMouseButton mb || !mb.Pressed)
		{
			return;
		}
		if (mb.ButtonIndex != MouseButton.WheelUp && mb.ButtonIndex != MouseButton.WheelDown)
		{
			return;
		}
		if (!GodotObject.IsInstanceValid(_carousel) || !_carousel.IsActiveCardVisible)
		{
			return;
		}

		int delta = (mb.ButtonIndex == MouseButton.WheelUp) ? -1 : +1;
		NavigateResult result = _carousel.TryNavigate(delta);

		switch (result)
		{
			case NavigateResult.Moved:
				// Index changed; keep Main's canonical index in lockstep with
				// the carousel and consume the event so a future zoom-on-wheel
				// doesn't also fire on this tick.
				_activeMissionIndex = _carousel.ActiveIndex;
				GetViewport().SetInputAsHandled();
				break;

			case NavigateResult.AtBound:
				// Clamped at a bound. Nothing to refresh but still consume —
				// the user's intent is "navigate missions", not "zoom map",
				// even when they hit the wall. Defensive against future zoom.
				GetViewport().SetInputAsHandled();
				break;

			case NavigateResult.NotVisible:
				// Should not reach here given the gate above, but defensively:
				// do not consume so something else can pick up the wheel.
				break;
		}
	}

	// At J2 the Halfgate pawn only reacts to the Halfgate POI — that's the only
	// mission we expect from tick 1 and the only painted iso art we have. Other
	// POIs hide the pawn so a stale Halfgate scene never lingers behind an
	// unrelated selection. J3+ will introduce per-POI pawns (one node per piece
	// of iso art) and this dispatcher will route by TargetPoi to the right one.
	private void OnMissionCellSelected(string targetPoi)
	{
		if (!GodotObject.IsInstanceValid(_halfgatePawn))
		{
			return;
		}

		if (targetPoi == "e1.halfgate")
		{
			_halfgatePawn.Show();
		}
		else
		{
			_halfgatePawn.Hide();
		}
	}

	private void OnMissionCellDeselected()
	{
		if (!GodotObject.IsInstanceValid(_halfgatePawn))
		{
			return;
		}
		_halfgatePawn.Hide();
	}

	// J3b / J4a / J7 companion handler. Kept as a named method (not a lambda)
	// so the same reference can be passed to -= in _ExitTree.
	private void OnHalfgatePawnEngaged()
	{
		// Push the latest (missions, index) into the carousel so its three
		// slots reflect the current state, then show it. SetActiveMission is
		// idempotent and cheap (3 rebind ops max) so calling it on every
		// engage is fine even if nothing changed.
		RefreshCarousel();
		if (GodotObject.IsInstanceValid(_carousel))
		{
			_carousel.Show();
		}
	}

	// J7: single source of truth for "what does the carousel currently show".
	// Called from OnHalfgatePawnEngaged (entry into the engaged state) and
	// from HandleTickResponse (after a tick adds a new mission while the
	// carousel may already be visible).
	//
	// Falls through the J3c "fall back to most-recent Halfgate mission" logic:
	// in J7 the carousel is a list view of ActiveMissions, so an empty list
	// just renders three hidden slots (no placeholder text). The legacy
	// ResolveHalfgateNarrativeHook fallback is no longer wired — the carousel
	// is honest about an empty list.
	private void RefreshCarousel()
	{
		if (!GodotObject.IsInstanceValid(_carousel))
		{
			return;
		}
		_carousel.SetActiveMission(_state.ActiveMissions, _activeMissionIndex);
	}

	private void OnHalfgatePawnReleased()
	{
		if (GodotObject.IsInstanceValid(_carousel))
		{
			_carousel.Hide();
		}
	}

	// J4a test harness — see the [NextTickButton] note in _Ready. Godot's
	// Button.Pressed signal fires on the main thread, but we immediately leave
	// it via the async fire-and-forget pattern (same discipline as _Ready ->
	// StartNewGame) so the UI never blocks on the HTTP round-trip.
	//
	// No re-entrancy guard: clicking the button mid-flight will queue a second
	// HTTP call. That's fine for a test harness.
	private void OnNextTickPressed()
	{
		_ = DoTickAsync(_cts.Token);
	}

	private async Task StartNewGame()
	{
		_state.StartNewGame();
		// Reset the navigation index and the tick counter in lockstep with the
		// cleared mission list. _currentTick = 1 so the very first POST sends
		// tick=1; DoTickAsync increments AFTER the call returns.
		_activeMissionIndex = 0;
		_currentTick = 1;

		await DoTickAsync(_cts.Token);
	}

	// J4a: the single tick-issuing path. Called both by StartNewGame on _Ready
	// and by OnNextTickPressed for every subsequent tick. Centralising it here
	// means the request shape, the post-await marshalling discipline, and the
	// mission-recording side effects stay in one place.
	private async Task DoTickAsync(CancellationToken ct)
	{
		int tickForThisCall = _currentTick;

		var mission = await BackendClient.PostWorldTick(
			tick: tickForThisCall,
			seed: _state.WorldSeed,
			contextProse: "The company enters Halfgate.",
			ct: ct
		);

		// The await above may resume off the main thread. From this point on
		// we only touch _state and primitive fields (plain C# — safe) and
		// defer all Godot work via CallDeferred.
		HandleTickResponse(tickForThisCall, mission);
	}

	// Synchronous tail of every tick. Mutates GameState, advances the tick
	// counter, logs, and schedules a deferred RefreshMissions on the overlay.
	private void HandleTickResponse(int tick, MissionData? mission)
	{
		_state.RecordTick(mission);
		_currentTick = tick + 1;

		// Clamp the navigation index in case ActiveMissions was mutated in a
		// way that invalidates it.
		if (_state.ActiveMissions.Count == 0)
		{
			_activeMissionIndex = 0;
		}
		else if (_activeMissionIndex >= _state.ActiveMissions.Count)
		{
			_activeMissionIndex = _state.ActiveMissions.Count - 1;
		}

		if (mission != null)
		{
			GD.Print($"Mission received (tick {tick}): [{mission.Type}] {mission.ToString()}");
		}
		else
		{
			GD.Print($"Tick {tick} returned no mission (or backend unreachable).");
		}

		// Snapshot the mission list so the deferred closure doesn't race with
		// later mutations on _state.ActiveMissions (e.g. a second Next Tick
		// press landing while this CallDeferred is still queued).
		var snapshot = new List<MissionData>(_state.ActiveMissions);

		Callable.From(() =>
		{
			if (GodotObject.IsInstanceValid(_overlay))
			{
				_overlay.RefreshMissions(snapshot);
			}
			// J7: if the carousel is visible right now (user is hovering the
			// pawn while a tick lands), push the new (missions, index) so the
			// new mission appears in a slot immediately. Critical for the
			// J4a test flow: accumulate missions by pressing Next Tick while
			// hovering, navigate them with the wheel without releasing.
			if (GodotObject.IsInstanceValid(_carousel) && _carousel.Visible)
			{
				_carousel.SetActiveMission(snapshot, _activeMissionIndex);
			}
		}).CallDeferred();
	}
}
