// Generated by hand from wayfinders/models.py @ 2026-04-24.
// STAGE 1 CONTRACT: keep in sync manually. Re-run scripts/dump_character.py
// and eyeball the diff when models.py changes. Stage 3 (FastAPI) will replace
// this with openapi-typescript output.
export type StatKey = "STR" | "DEX" | "WIS";

export type Stats = Record<StatKey, number>;

export type VoteTendency = "keep" | "risk assessment" | "banish on cost";
export type RollKind = "risky" | "safe" | "loot";

export interface Background {
  name: string;
  stat_adjustments: Partial<Record<StatKey, number>>;
  starting_equipment: string[];
  incapabilities: string[];
}

export interface Trait {
  name: string;
  roll_modifier: Partial<Record<RollKind, number>>;
  menu_tag_boosted: string[];
  menu_tag_suppressed: string[];
  stress_modifier: number;
  vote_tendency: VoteTendency;
  contradicts: string[];
}

export interface Item {
  id: string;
  name: string;
  category: string;
  stat_bonus: Partial<Record<StatKey, number>>;
  tier: number;
  tags: string[];
  armor_value: number;
  uses_until_degradation: number;
  is_provision: boolean;
}

export interface Character {
  id: string;
  name: string;
  stats: Stats;
  max_hp: number;
  current_hp: number;
  background: Background;
  traits: Trait[];
  inventory: Item[];
  stress: number;
  current_mission_id: string | null;
  conditions: string[];
  recovery_clock_ids: Record<string, string>;
  mission_history: string[];
  backstory_hook: string | null;
  portrait_id: string | null;
}
